spring:
  config:
    activate:
      on-profile: "local"
  profiles:
    include:
      - "core-local"

# Logging Info
logging:
  level:
    org.springframework: debug

springdoc:
  swagger-ui:
    path: "/swagger-ui"
  api-docs:
    path: "/api-docs"